# Generated by Django 5.0.1 on 2024-02-03 14:45

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAppDetails',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('organization_name', models.CharField(max_length=255)),
                ('repository_name', models.CharField(max_length=255)),
                ('branch_name', models.CharField(max_length=255)),
                ('app_name', models.CharField(max_length=255)),
                ('region', models.CharField(max_length=255)),
                ('framework', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='app',
            name='branch_id',
        ),
        migrations.RemoveField(
            model_name='plan',
            name='app_id',
        ),
        migrations.RemoveField(
            model_name='repository',
            name='organization_id',
        ),
        migrations.AddField(
            model_name='plan',
            name='database_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.database'),
        ),
        migrations.AddField(
            model_name='plan',
            name='user_app',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.userappdetails'),
        ),
        migrations.AlterField(
            model_name='environmentvariable',
            name='app_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.userappdetails'),
        ),
        migrations.DeleteModel(
            name='Branch',
        ),
        migrations.DeleteModel(
            name='Organization',
        ),
        migrations.DeleteModel(
            name='Repository',
        ),
        migrations.DeleteModel(
            name='App',
        ),
    ]
