# Generated by Django 5.0.1 on 2024-02-03 14:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_userappdetails_remove_app_branch_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='environmentvariable',
            name='app_id',
        ),
        migrations.RemoveField(
            model_name='plan',
            name='user_app',
        ),
        migrations.AddField(
            model_name='userappdetails',
            name='database_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.database'),
        ),
        migrations.AddField(
            model_name='userappdetails',
            name='environment_variables',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.environmentvariable'),
        ),
        migrations.AddField(
            model_name='userappdetails',
            name='plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.plan'),
        ),
    ]
