# Generated by Django 5.0.1 on 2024-02-03 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_environmentvariable_app_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plan',
            name='database_id',
        ),
    ]
