# Generated by Django 5.0.1 on 2024-02-03 14:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_remove_plan_database_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userappdetails',
            name='environment_variables',
        ),
        migrations.AddField(
            model_name='environmentvariable',
            name='user_app',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.userappdetails'),
        ),
    ]
