# Generated by Django 5.0.1 on 2024-02-03 16:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_remove_userappdetails_environment_variables_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userappdetails',
            name='database_type',
            field=models.ForeignKey(default='13fb20f2-c54e-4016-a9c3-fbda63d6fb84', on_delete=django.db.models.deletion.CASCADE, to='app.database'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userappdetails',
            name='plan',
            field=models.ForeignKey(default='fd1eb9fb-8753-442d-9171-032313996fc7', on_delete=django.db.models.deletion.CASCADE, to='app.plan'),
            preserve_default=False,
        ),
    ]
