# Generated by Django 5.0.1 on 2024-02-04 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_userappdetails_environment_variables'),
    ]

    operations = [
        migrations.AlterField(
            model_name='environmentvariable',
            name='key',
            field=models.CharField(max_length=255),
        ),
    ]
