# Generated by Django 5.0.1 on 2024-02-04 07:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_environmentvariable_key'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userappdetails',
            name='environment_variables',
        ),
    ]
